# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  custom = {
    hardware = {
      nvidia.enable = true;
      nvidiaHybridWithIntelOffLoadMode.enable = true;
      # I am using intel hardware decoding as I am not sure my nvidia chip supports it, prime in offload mode is not working
      # for both VA-API and VDPAU , and I have not tried to use prime in sync mode. As at the moment I don't need
      # hardware decoding I am fine with using the intel gpu settings which work just fine.
      intelHardwareDecoding.enable = true;

      cpuVendor = "intel";
      nvidiaHybridWithIntel = {
        nvidiaBusId = "PCI:01:00:0";
        intelBusId = "PCI:00:02:0";
      };
    };
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
