# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../modules/nixos/hardware/host_platform.nix
    ../../modules/nixos/hardware/dhcp-setup.nix
    ../../modules/nixos/hardware/intel-microcode.nix
    ../../modules/nixos/gpu/nvidia.nix
    ../../modules/nixos/gpu/nvidia_hybrid_with_intel_offload_mode.nix
    # I am using interl hardware decoding as I am not sure my nvidia chip supports it, prime in offload mode is not working
    # for both VA-API and VDPAU , and I have not tried to use prime in sync mode. As at the moment I don't need
    # hardware decoding I am fine with using the intel gpu settings which work just fine.
    ../../modules/nixos/gpu/intel_hardware_decoding.nix
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
