keys:
  - &work_pc age1960hm9pdxgckwey2t0ch8uzjd6v8jf07nuv84karpap4g3kqm3kqnqavew
  - &home_desktop age1203qrs9tl0nuc94jq3pvk38n6cmuu947a489jf7y6n3xfwq3mqhq2rcajv
  - &homelab age16dp952aecvxguqj8xz4mh2akakfe7py5l7j77akx6zhygt3mefls2ex4vy
  - &generic_linux_distro age1jukh2jtz084zgvzkq398frz73qjr9cjnljhsdsw70ywy5kxp7pnsls0eja
  - &vm_server age1lj7hv8aql2cepq3u5n2v280dqnlwztl8xgr5uz9pvpc59tfqqahq3kzz8x
creation_rules:
  - path_regex: machines/work_pc/secrets.yaml$
    key_groups:
      - age:
        - *work_pc
  - path_regex: machines/home_desktop/secrets.yaml$
    key_groups:
      - age:
        - *home_desktop
  - path_regex: machines/homelab/secrets.yaml$
    key_groups:
      - age:
        - *homelab
  - path_regex: machines/homelab/secrets.json$
    key_groups:
      - age:
        - *homelab
  - path_regex: prowlarr\.db$
    key_groups:
      - age:
        - *homelab
  - path_regex: machines/generic_linux_distro/secrets.yaml$
    key_groups:
      - age:
        - *generic_linux_distro
  - path_regex: machines/vm_server/secrets.yaml$
    key_groups:
      - age:
        - *vm_server

