# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  ...
}:
{
  imports = [
  (modulesPath + "/profiles/qemu-guest.nix")
  ../../modules/nixos/hardware/host_platform.nix
  ../../modules/nixos/hardware/dhcp-setup.nix
  ../../modules/nixos/hardware/intel-microcode.nix
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];
}
